name: creating CI-CD for Jitsi React 
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    # - run: npm test

    - name: Extract short commit hash
      id: vars
      run: |
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-5)
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV
    - name: Set Commit Hash
      run: echo "COMMIT_HASH=${{ env.SHORT_SHA }}" >> $GITHUB_ENV

    - name: Log in to Docker Hub
      run: echo ${{ vars.DOCKER_PASSWORD }} | docker login -u ${{ vars.DOCKER_USERNAME }} --password-stdin

    - name: Build and push Docker image
      run: |
          docker build -t expotechx/jitsi:${{ env.SHORT_SHA }} .
          docker push expotechx/jitsi:${{ env.SHORT_SHA }}
